version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10

    working_directory: /go/src/github.com/tendermint/ethermint

    steps:
      - checkout

      - run:
          name: "Run ci"
          command: make ci
